Fixed setup_wizard and read_config() Use maxibuild for script dependency

diff --git a/aipdb b/aipdb
--- a/aipdb
+++ b/aipdb
@@ -1,7 +1,7 @@
 #!/bin/bash
 # ==================================================
 _APP_SPECIFIC_NAME="AbuseIPDB"
-_APP_VERSION="0.6"
+_APP_VERSION="0.7"
 _APP_STATUS="beta"
 _APP_INFO="${_APP_SPECIFIC_NAME} (aipdb) is bash script to manage AbuseIPDB API"
 _APP_VERSION_STATUS="${_APP_VERSION}-${_APP_STATUS}"
@@ -184,9 +184,9 @@ setup_wizard() {
   if [[ "${answer}" == "y" || "${answer}" == "Y" ]]; then
     # Copy the sample config file from template
     info 1 "Converting config file into unix format"
-    sed -i 's/\r$//' "${CONFIG_FILE}".sample
+    sed -i 's/\r$//' "${SCRIPT_PATH}/${SCRIPT_NAME}.conf.sample"
     info 1 "Copying sample config file from template ..."
-    cp -f "${SCRIPT_PATH}/aipdb.conf.sample" "${CONFIG_FILE}"
+    cp -f "${SCRIPT_PATH}/${SCRIPT_NAME}.conf.sample" "${CONFIG_FILE}"
     retval=$?
     info 1 "Using config file: ${CONFIG_FILE}"
     if [ "${retval}" -eq 0 ]; then
@@ -219,8 +219,8 @@ read_config() {
   caller="${SCRIPT_NAME}->${FUNCNAME[0]}"
 
   if [[ -z "${CONFIG_FILE}" ]]; then
-    info 2 "Using default config file: ${SCRIPT_PATH}/aipdb.conf"
-    CONFIG_FILE="${SCRIPT_PATH}/aipdb.conf"
+    info 2 "Using default config file: ${SCRIPT_PATH}/${SCRIPT_NAME}.conf"
+    CONFIG_FILE="${SCRIPT_PATH}/${SCRIPT_NAME}.conf"
   else
     info 2 "Using config file: ${CONFIG_FILE}"
   fi
@@ -267,7 +267,7 @@ scan() {
 
   caller="${SCRIPT_NAME}->${FUNCNAME[0]}"
   if [ -z "${TARGET}" ]; then
-    error "No target specified (eg: aipdb check --target 1.2.3.4 or aipdb check --domain example.com)"
+    error "No target specified (eg: ${SCRIPT_NAME} check --target 1.2.3.4 or ${SCRIPT_NAME} check --domain example.com)"
   fi
 
   ip_lookup=$(resolve "${TARGET}")
@@ -275,9 +275,9 @@ scan() {
   if [[ -z "${ip_lookup}" ]]; then
     error "[${caller}]: No DNS record found for ${TARGET}"
   elif [[ "${ip_lookup}" != "${TARGET}" ]]; then
-    info 1 "[${caller}]: Using IP address ${ip_lookup} for target, resolved from ${TARGET}"
+    info 1 "Using IP address ${ip_lookup} for target, resolved from ${TARGET}"
   else
-    info 1 "[${caller}]: Using IP address ${TARGET} for target"
+    info 1 "Using IP address ${TARGET} for target"
   fi
 
   # Make sure that the output file is limited to ABUSEIPDB_OUTPUT_MAX_LIMIT (delete the oldest record)
@@ -293,7 +293,7 @@ scan() {
     fi
   fi
 
-  info 0 "[${caller}]: Checking target IP address ${ip_lookup} ..."
+  info 0 "Checking target IP address ${ip_lookup} ..."
 
   target=""
   ip_address=""
@@ -625,7 +625,7 @@ OS_TEMP_PATH="/tmp"
 
 mkdir -p "${OS_TEMP_PATH}"
 
-SHORT_OPT_SPECS=":hvpsjc:o:kt:-:"
+SHORT_OPT_SPECS=":hvsjc:o:kt:-:"
 LONG_OPT_SPECS=(["ip"]=1 ["ip-address"]=1 ["domain"]=1 ["domain-name"]=1 ["config"]=1 ["target"]=1 ["category"]=1 ["categories"]=1 ["comment"]=1 ["output"]=1)
 INDEX=$(($# + 1))
 
@@ -639,15 +639,12 @@ SCRIPTING=false
 
 # Make sure jq and ipcalc are installed
 
-if ! command -v jq &>/dev/null; then
-  echo "jq could not be found. Please install jq first."
+if ! command -v maxibuild &>/dev/null; then
+  echo "Error, maxibuild is not installed, please install it first"
   exit 1
 fi
 
-if ! command -v ipcalc &>/dev/null; then
-  echo "ipcalc could not be found. Please install ipcalc first."
-  exit 1
-fi
+maxibuild --include "jq ipcalc"
 
 RESPONSE_FILE="$(mktemp)"
 
